# Generated by Django 4.2.6 on 2023-10-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_active_remove_course_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='courses/%y/%m'),
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=None, upload_to='courses/%y/%m'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'course')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='update_date',
        ),
    ]
