# Generated by Django 4.2.6 on 2024-01-26 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_lesson_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
    ]
